#!/bin/bash
# differr
if [ -f tests/bytecode/*/$1.err ]; then
  diff -uN tests/bytecode/*/$1.err tmp.err.$1  | less
  exit 0
fi

if [ -f tests/*/$1.err ]; then
  diff -uN tests/*/$1.err tmp.err.$1  | less
  exit 0
fi


echo $1 not found
