#! /usr/bin/python
# test calling an unknown method
import sys
import dbus
T_o = dbus.SessionBus().get_object('org.opensuse.YaST.modules',
                                   '/org/opensuse/YaST/modules/TEST')
T = dbus.Interface(T_o, 'org.opensuse.YaST.Values')
try:
  T.NoSuchMethod()
except dbus.exceptions.DBusException, e:
  if e.get_dbus_name() == 'org.freedesktop.DBus.Error.UnknownMethod':
    print e
    sys.exit(0)
  raise # Unexpected DBusException
assert False # We should have got an exception instead
