#! /bin/sh
# run all applicable test cases with proper setup
# $0 [-a: all, even failing]
# $0 ./a_single_testcase

# stress test iterations
if [ "$1" = "-s" ]; then
    STRESS=${2-10}
    shift
    shift
fi

if [ "$1" = "" ]; then
  : ${CASES:=./t[12345]*}
elif [ "$1" = "-a" ]; then
  : ${CASES:=./t? ./t*-*}
else
  : ${CASES:=$@}
fi
CASES_A=($CASES)		 # make array
CASES_A=(${CASES_A[@]/*~/})	 # exclude backup files
if ! which python; then
  echo >&2 "Python not found, skipping those tests"
  CASES_A=(${CASES_A[@]/*.py/})	 # exclude python files
fi
# load the modules from the current directory
export Y2DIR=.
SVRDIR=../src
SVR=$SVRDIR/yast_modules_dbus_server
if [ -n "$STRESS" ]; then
  SVR="-s $STRESS valgrind --leak-check=full $SVRDIR/.libs/yast_modules_dbus_server"
fi
./test_server \
	$SVR --disable-timer --test TEST \
	-- \
	${CASES_A[@]}
