#!/usr/bin/perl
#
# Author: Jan Holesovsky <kendy@suse.cz>, 2001
#
# Agent for reading modinfo of modules in the directory
# /lib/modules/`uname -r`/
#
# $Id$

use lib "/usr/lib/YaST2/agents_non_y2";
use ycp;

my $result;

my $modules_prefix = "/lib/modules/".qx(/bin/uname -r | /usr/bin/tr -d '\n');

while ( <STDIN> )
{
    # ycpDoVerboseLog();

    ycpInit( $_ );

    my $path = my $module_name = ycpGetPath;
    $path =~ s/\./\//g;
    $module_name =~ s/^.*\.//;

    $path = $modules_prefix.$path;
    y2debug( "ag_modinfo. Using: ", $path );

    #----------------------------------------------------------
    #  Check the Command
    #----------------------------------------------------------

    if ( ycpCommandIsDir )
    {
	my $list_mod = qx(cd $path 2> /dev/null ; ls *.o 2> /dev/null);
	$list_mod =~ s/\.o//g;

	my @list = split("\n", $list_mod);

	ycp::Return ( \@list );
    }
    elsif ( ycpCommandIsRead )
    {
	# full name of the module
	my $modinfo = qx(/sbin/modinfo $module_name 2> /dev/null);

	my @list = split("\n", $modinfo);

	my %mod = ();
	foreach $_ (@list)
	{
	    my $desc = $_;
	    $desc =~ s/^[^:]*:\s*//;
	    $desc =~ s/^[^"]*"//;
	    $desc =~ s/".*$//;

	    if (/^filename/)
	    {
		$mod{"module_filename"} = $desc;
	    }
	    if (/^description/)
	    {
		$mod{"module_description"} = $desc;
	    }
	    if (/^author/)
	    {
		$mod{"module_author"} = $desc;
	    }
	    if (/^parm/)
	    {
		my $key = $_;
		$key =~ s/^[^:]*:\s*(\S*).*/$1/;
		if (/"/)
		{
		    $mod{$key} = $desc;
		}
		else
		{
		    $mod{$key} = "";
		}
	    }
	}

	ycp::Return ( \%mod, 1 );

    }

    # result: we must exit
    elsif (ycpCommandIsResult)
    {
	y2debug ("got result -> say goodbye!");
	exit;
    }

    else
    {
	my $return_value = sprintf( "Unknown instruction %s or argument: %s", ycpGetCommand, ycpGetArgType);

	ycp::Return( $return_value );
    }
}

# end
