#!/usr/bin/expect --
# try to test bug #263308

source test-common.exp

send "`Execute(.run_output_err, \"echo O; echo O; sleep 1; echo OUT; echo >&2 ERR; exit 2\")\r"
expect "(true)$"

while {1} {
    send "`Read(.isrunning)\r"
    expect {
	"(true)$" {sleep 1}
	"(false)$" break
    }

}

send "`Read(.pid)\r"
expect "(-1)$"
#send_user "\n"

send "`Read(.store)\r"
expect "(true)$"
send "`Read(.status)\r"
expect "(2)$"

send "`Read(.lines)\r"
expect "(3)"
# bug in original agent
expect -re "(\"\")?$"
send "`Read(.lines_err)\r"
expect "(1)$"
send "`Read(.newlines)\r"
expect "(3)$"
send "`Read(.newlines_err)\r"
expect "(1)$"
send "`Read(.newout)\r"
expect -ex "\[\"O\",\"O\",\"OUT\",\] "
send "`Read(.newerr)\r"
expect -ex "\[\"ERR\",\] "

send "`Read(.output_open)\r"
expect "(false)$"
send "`Read(.output_open_err)\r"
expect "(false)$"
send "`result(true)\r"
expect eof
