#!/usr/bin/expect --
# test bug #263308
# the old agent only checks the exit status when closing a pipe, not on SIGCHLD

source test-common.exp

#send "`Execute(.run_output_err, \"echo O; echo O; exec 1<&-; sleep 2; echo >&2 ERR; exit 113\")\r"
send "`Execute(.run_output_err, \"echo OUT; echo OUT; echo >&2 ERR; exec 1<&- 2<&-; sleep 2; exit 113\")\r"
expect "(true)$"

while {1} {
    send "`Read(.isrunning)\r"
    expect {
	"(true)$" {sleep 1}
	"(false)$" break
    }

}

send "`Read(.status)\r"
expect "(113)$"

send "`Read(.newout)\r"
expect -ex "\[\"OUT\",\"OUT\",\] "
send "`Read(.newerr)\r"
expect -ex "\[\"ERR\",\] "

send "`Execute(.kill, \"\")\r"
expect "(false)$"

send "`result(true)\r"
expect eof
