#!/usr/bin/expect --
# test ...

source test-common.exp

send "`Write(.buffer_size, 10)\r";
expect "(true)$"
send "`Write(.buffer_size_err, 10)\r";
expect "(true)$"

send "`Execute(.run_output_err, \"seq 100 199; seq 200 249 >&2; exec 1<&- 2<&-; sleep 2; exit 113\")\r"
expect "(true)$"

while {1} {
    send "`Read(.isrunning)\r"
    expect {
	"(true)$" {sleep 1}
	"(false)$" break
    }

}

send "`Read(.status)\r"
expect "(113)$"

send "`Read(.newlines)\r"
expect "(100)$"
send "`Read(.newlines_err)\r"
expect "(50)$"

send "`Execute(.kill, \"\")\r"
expect "(false)$"

send "`result(true)\r"
expect eof
