# common setup for test cases of ag_backgound

set prog "../ag_background"
set env(PERL5LIB) "../lib"

if {[lindex $argv 0] == "-u"} {
    # -u: use the old one in /usr
    set prog "/usr/lib/YaST2/servers_non_y2/ag_background"
    set argv [lrange $argv 1 end];	# shift
}
# can pass -d
spawn $prog $argv

# enlarge your input buffer now! satisfaction guaranteed! give us your $$$
match_max 100000

set timeout 15
expect_after {    
    default {
	puts "OOPS"
	puts "last matched <<$expect_out(buffer)>>"
	exit 1
    }
}
