# common setup for test cases of ag_backgound

if { [catch {exec grep devpts.*mode=620 /proc/mounts} ] } {
    # Something in our Jenkins instance remounts it with mode 600
    # and then "spawn" fails.
    puts "SKIP: need devpts with mode=620."
    puts "  See also https://bugzilla.redhat.com/show_bug.cgi?id=510183"
    exit 77
}

set prog "../ag_background"
set env(PERL5LIB) "../lib"

if {[lindex $argv 0] == "-u"} {
    # -u: use the old one in /usr
    set prog "/usr/lib/YaST2/servers_non_y2/ag_background"
    set argv [lrange $argv 1 end];	# shift
}
# can pass -d
spawn $prog $argv

# enlarge your input buffer now! satisfaction guaranteed! give us your $$$
match_max 100000

set timeout 15
expect_after {
    default {
	puts "OOPS"
	puts "last matched <<$expect_out(buffer)>>"
	exit 1
    }
}
