# common setup for test cases of ag_backgound

# enlarge your input buffer now! satisfaction guaranteed! give us your $$$
match_max 100000

set timeout 3
expect_after {    
    default {
	puts "OOPS"
	puts "last matched <<$expect_out(buffer)>>"
	exit 1
    }
    # pass thru agent stderr
#    -i $error_spawn_id
#    default {send_user $expect_out(buffer)}
}

#stty -echo

set prog "../ag_background"

# does not work
#spawn "sh" "-c" "PERLDB_OPTS='NonStop=1 AutoTrace=1 frame=6' perl -dS $prog"

if {[lindex $argv 0] == "-u"} {
    # -u: use the old one in /usr
    set prog "/usr/lib/YaST2/servers_non_y2/ag_background"
    set argv [lrange $argv 1 end];	# shift
}
# can pass -d
spawn $prog $argv

