#
# bytecode.exp
# 'main' file for all bytecode tests
#

set directories { constants expressions statements imports Xmodules }
#set directories { constants expressions statements imports Xmodules }

# compile the modules first
foreach file [get-files $srcdir/tests/ bytecode/Module "ycp" ] {
    bytecode-compile $file tests/bytecode/Module
}

foreach dir $directories {
    set filenames [get-files $srcdir/tests bytecode/$dir "ycp" ]
    foreach file $filenames {
	if {[bytecode-run $file tests/bytecode/$dir] < 0} {
#	    return -1;
	} 
#	bytecode-run $file tests/bytecode/$dir
    }
}
puts ""
