#
# ycp.exp
# 'main' file for all ycp tests
#

set directories { builtin errors expressions includes modules scope statements types values }


# original line
#set directories { builtin errors expressions includes modules scope statements types values }

# compile the modules first
foreach file [get-files $srcdir/tests/ Module "ycp" ] {
    bytecode-compile $file tests/Module
}

foreach dir $directories {
    set filenames [get-files $srcdir tests/$dir "ycp" ]
    foreach file $filenames {
#	if {[ycp-run $file tests/$dir] != 0} {
#	    return -1;
#	} 
	ycp-run $file tests/$dir
    }
}
