#!/bin/bash

# exec 2>/dev/null

while true ; do
    IFS=
    read COMMAND || exit
    unset IFS
    
    case "$COMMAND" in
	"result ("*)
	    exit
	    ;;
	'Read (.username)')
	    echo '"'"$(whoami)"'"'
	;;
	*)
	    echo nil
    esac
done
